main_menu:
  - prompt: "󰀻 Apps"
    command: "apps"
  - prompt: " Config"
    command: "config"
  - prompt: " Font"
    command: "font"
  - prompt: " System"
    command: "system"
  - prompt: "󰸌 Theme"
    command: "theme"
  - prompt: " Screenshot"
    command: "screenshot"
  - prompt: "󰔎 Toggle"
    command: "toggle"
  - prompt: "󰭌 Packages"
    command: "package"
  - prompt: "󰱔 Default"
    command: "default"
system_menu:
  - prompt: " Lock"
    command: "loginctl lock-session"
  - prompt: " Suspend"
    command: "systemctl suspend"
    confirm: "Suspend system?"
  - prompt: "󰈆 Logout"
    command: "hyprctl dispatch exit"
    confirm: "Logout?"
  - prompt: " Reboot"
    command: "systemctl reboot"
    confirm: "Reboot system?"
  - prompt: "󰐥 Shutdown"
    command: "systemctl poweroff"
    confirm: "Shutdown system?"
config_menu:
  - prompt: " Alacritty"
    command: "/alacritty/alacritty.toml"
  - prompt: " Dunst"
    command: "/dunst/dunstrc"
  - prompt: " Hypridle"
    command: "/hypr/hypridle.conf"
  - prompt: " Hyprland"
    command: "/hypr/hyprland.conf"
  - prompt: " Kitty"
    command: "/kitty/kitty.conf"
  - prompt: " Rofi"
    command: "/rofi/config.rasi"
  - prompt: " Waybar"
    command: "/waybar/config.jsonc"
  - prompt: " Zsh"
    command: "/zsh/.zshrc"
default_menu:
  - prompt: " Terminal"
    command: "terminal"
  - prompt: " Browser"
    command: "browser"
  - prompt: " Editor"
    command: "editor"
default_editor_menu:
  - prompt: " NeoVim"
    command: "hyperion-default-editor nvim"
  - prompt: " Vim"
    command: "hyperion-default-editor vim"
default_browser_menu:
  - prompt: "󰊯 Google Chrome"
    command: "hyperion-default-browser chrome"
  - prompt: "󰖟 Zen"
    command: "hyperion-default-browser zen"
default_terminal_menu:
  - prompt: " Alacritty"
    command: "hyperion-default-terminal alacritty"
  - prompt: " Kitty"
    command: "hyperion-default-terminal kitty"
package_menu:
  - prompt: "Install Package"
    command: "hyperion-pkg-install"
  - prompt: "Remove Package"
    command: "hyperion-pkg-remove"
  - prompt: "Install AUR Package"
    command: "hyperion-pkg-aur-install"
screenshot_menu:
  - prompt: "Region"
    command: "cmd-screenshot"
  - prompt: "Window"
    command: "cmd-screenshot window"
  - prompt: "Display"
    command: "cmd-screenshot output"
