main_menu:
  - name: '󰀻 Apps'
    command: 'apps'
  - name: ' Config'
    command: 'config'
  - name: ' Font'
    command: 'font'
  - name: ' System' 
    command: 'system'
  - name: '󰸌 Theme' 
    command: 'theme'
  - name: ' Screenshot' 
    command: 'screenshot'
  - name: '󰔎 Toggle' 
    command: 'toggle'
  - name: '󰭌 Packages'
    command: 'package'
  - name: '󰱔 Default'
    command: 'default'
system_menu:
  - prompt: ' Lock'     
    command: 'loginctl lock-session'
  - prompt: ' Suspend'  
    command: 'systemctl suspend' 
    confirm: 'Suspend system?'
  - prompt: '󰈆 Logout'
    command: 'hyprctl dispatch exit'
    confirm: 'Logout?'
  - prompt: ' Reboot'
    command: 'systemctl reboot'
    confirm: 'Reboot system?'
  - prompt: '󰐥 Shutdown'
    command: 'systemctl poweroff'
    confirm: 'Shutdown system?'
config_menu:
  - prompt: ' Alacritty' 
    command: '/alacritty/alacritty.toml'
  - prompt: ' Dunst' 
    command: '/dunst/dunstrc'
  - prompt: ' Hypridle' 
    command: '/hypr/hypridle.conf'
  - prompt: ' Hyprland' 
    command: '/hypr/hyprland.conf'
  - prompt: ' Kitty' 
    command: '/kitty/kitty.conf'
  - prompt: ' Rofi' 
    command: '/rofi/config.rasi'
  - prompt: ' Waybar' 
    command: '/waybar/config.jsonc'
  - prompt: ' Zsh' 
    command: '/zsh/.zshrc'
pkg_menu:
  - prompt: 'Install package'
    command: 'hyperion-pkg-install'
default_menu:
  - prompt: ' Terminal'
    command: 'terminal'
  - prompt: ' Browser'
    command: 'browser'
  - prompt: ' Editor'
    command: 'editor'
default_editor_menu:
  - prompt: ' NeoVim'
    command: 'hyperion-default-editor nvim'
  - prompt: ' Vim'
    command: 'hyperion-default-editor vim'
default_browser_menu:
  - prompt: '󰊯 Google Chrome'
    command: 'hyperion-default-browser chrome'
  - prompt: '󰖟 Zen'
    command: 'hyperion-default-browser zen'
default_terminal_menu:
  - prompt: ' Alacritty'
    command: 'hyperion-default-terminal alacritty'
  - prompt: ' Kitty'
    command: 'hyperion-default-terminal kitty'
package_menu:
  - prompt: 'Install Package'
    command: 'hyperion-pkg-install'
  - prompt: 'Remove Package'
    command: 'hyperion-pkg-remove'
  - prompt: 'Install AUR Package'
    command: 'hyperion-pkg-aur-install'
